import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Backend Developer',
    company: 'Otoanaliz',
    logo: '/images/careers/otoanaliz.png',
    location: 'Istanbul, Turkey',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2024.02',
    end_date: null,
    industry: 'Insurance',
    link: 'https://otoanaliz.net/',
  },
  {
    position: 'Backend Developer',
    company: 'Freelance',
    logo: '/images/goktugcy.jpeg',
    location: 'Istanbul, Turkey',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2023.10',
    end_date: '2024.01',
    industry: 'Software Development',
    link: null,
  },
  {
    position: 'Backend Developer',
    company: 'Beyond',
    logo: '/images/careers/beyond.webp',
    location: 'Istanbul, Turkey',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2022.09',
    end_date: '2023.09',
    industry: 'Software Agency',
    link: 'https://beyond.codes/',
  },
  {
    position: 'PHP Developer',
    company: 'As Bilişim Teknolojileri',
    logo: '/images/careers/Asbilisim.png',
    location: 'Istanbul, Turkey',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2022.09',
    end_date: '2023.09',
    industry: 'Software Agency',
    link: 'https://asbilisim.com.tr/',
  },
];
